export const TOGGLE_POST_FILTER = "TOGGLE_POST_FILTER";
export const SET_VIEW_POST = "SET_VIEW_POST";
export const CLEAR_VIEW_POST = "CLEAR_VIEW_POST";
export const GET_REQUESTED_POST = "GET_REQUESTED_POST";
