export const GET_SELECTED_TAGS = "GET_SELECTED_TAGS";
export const GET_ALL_TAGS = "GET_ALL_TAGS";
export const SET_SELECTED_TAG = "SET_SELECTED_TAGS";
export const REMOVE_SELECTED_TAG = "REMOVE_SELECTED_TAGS";
export const SAVE_SELECTED_TAGS = "SAVE_SELECTED_TAGS";
