export const ADD_COMMENT = "ADD_COMMENT"; // FOR ADDING COMMENT
export const SET_COMMENTS = "SET_COMMENTS"; // FOR SETTING COMMENTS ON VIEW POST LOAD
export const SET_POST_ID = "SET_POST_ID"; // SETTING POST_ID FOR GETTING COMMENTS OF THAT POST ONLY
export const CLEAR_POST_ID = "CLEAR_POST_ID"; // CLEARING POST ID AFTER CLICKING BACK BUTTON (ON VIEWPOST)
