export const GETUSER = "GETUSER";
export const SETUSER = "SETUSER";
export const CLEARUSER = "CLEARUSER";
export const SAVETOPICS = "SAVETOPICS";
export const EDITABLEUSER = "EDITABLEUSER";
export const CLEAREDITABLEUSER = "CLEAREDITABLEUSER";
